"""
Advanced Bayesian Methods Comparison
======================================

Three methods that differ fundamentally from the existing Bayesian BB:

  Existing BB:  Per-student Beta posteriors + temporal decay (γ=0.97)
                + cooldown penalty + empirical Bayes hyperprior refresh

  NEW ─────────────────────────────────────────────────────────────────
  1. Hierarchical Bayesian (HB)
       Students share a global hyperprior estimated from training data.
       "Partial pooling" — rare students borrow strength from frequent ones.
       Hyperparameters μ₀, κ₀ estimated via Method of Moments (empirical Bayes).
       No cooldown, no decay. Pure structural prior.

  2. Dirichlet Process Mixture (DPM)
       Non-parametric clustering: students grouped by selection pattern.
       Each cluster k has Beta(a_k, b_k) calling probability.
       Students are soft-assigned to clusters via variational EM.
       Prediction: P(s) = Σ_k r[s,k] · θ_k  (marginalised over clusters)
       New clusters can capture teacher "favourite groups" patterns.

  3. Pure Thompson Sampling (PTS)
       No decay, no cooldown. Beta-Binomial conjugate with uniform prior.
       Groups generated by sampling θ ~ Beta(α, β) → top-6.
       Each candidate group is independent → natural diversity.
       Cleanest comparison: what does Thompson Sampling alone buy?

Benchmarks (100-day fair evaluation):
  Bayesian BB   = 26.33%
  Hybrid Orig   = 26.83%

Usage:
    cd dl_pipeline
    python advanced_bayesian/run_advanced_bayesian.py
"""

from __future__ import annotations
import sys
from pathlib import Path

_THIS_DIR = Path(__file__).resolve().parent
_DL_DIR   = _THIS_DIR.parent
sys.path.insert(0, str(_DL_DIR))

import numpy as np
import pandas as pd
import time

# ── Config ────────────────────────────────────────────────────────────────────
SEED = 42
np.random.seed(SEED)
RNG  = np.random.default_rng(SEED)

CFG = {
    'excel_path':    str(_DL_DIR.parent / 'Database.xlsx'),
    'n_students':    55,
    'k':             6,
    'n_groups':      5,
    'train_ratio':   0.9,
    'n_sim_days':    100,
    'temperature':   1.5,
}

BENCHMARKS = {
    'Bayesian BB  (existing)': 26.33,
    'Hybrid Orig  (existing)': 26.83,
}


# ── Data ──────────────────────────────────────────────────────────────────────

def load_binary() -> np.ndarray:
    df = pd.read_excel(CFG['excel_path'])
    df = df.sort_values('Days').reset_index(drop=True)
    n_days = len(df)
    binary = np.zeros((n_days, CFG['n_students']), dtype=np.float32)
    id_cols = [c for c in df.columns if c.startswith('Student ID')]
    for row_idx, row in df.iterrows():
        for col in id_cols:
            sid = int(row[col]) - 1
            if 0 <= sid < CFG['n_students']:
                binary[row_idx, sid] = 1.0
    return binary


# ── Shared helpers ────────────────────────────────────────────────────────────

def _groups_from_probs(probs: np.ndarray) -> list[list[int]]:
    """Temperature-scaled diverse group generation (n_groups candidates)."""
    N, k, ng, T = CFG['n_students'], CFG['k'], CFG['n_groups'], CFG['temperature']
    p = np.clip(probs, 1e-9, None) ** (1.0 / T)
    p /= p.sum()
    groups: list[list[int]] = []
    for _ in range(ng * 4):
        g = sorted(np.random.choice(N, k, replace=False, p=p).tolist())
        if g not in groups:
            groups.append(g)
        if len(groups) >= ng:
            break
    if not groups:
        groups.append(sorted(np.argsort(probs)[-k:].tolist()))
    return groups[:ng]


def _best_overlap(groups: list[list[int]], actual: set) -> float:
    return max(len(set(g) & actual) for g in groups) / CFG['k']


# ══════════════════════════════════════════════════════════════════════════════
# 1. Hierarchical Bayesian
# ══════════════════════════════════════════════════════════════════════════════

class HierarchicalBayesian:
    """
    Beta-Binomial with empirical Bayes global hyperprior.

    Generative model:
        μ₀, κ₀  ← estimated from training data (Method of Moments)
        θ_s     ~ Beta(μ₀·κ₀,  (1-μ₀)·κ₀)       ← student prior
        x_s     ~ Bernoulli(θ_s)                  ← observation

    Posterior (conjugate):
        θ_s | data ~ Beta(μ₀·κ₀ + S_s,  (1-μ₀)·κ₀ + F_s)

    Key property:
        κ₀ controls shrinkage. Rare students (small n_s) are pulled toward
        μ₀; frequent students dominate their own data.
        The existing BB uses a fixed uniform prior (κ = 2); here κ is
        data-driven and can be much larger (stronger pooling).
    """

    def __init__(self, n_students: int = 55):
        base = 6.0 / n_students
        self.mu0   = base
        self.kappa = 10.0
        self.N     = n_students
        self.S = np.zeros(n_students, dtype=np.float64)
        self.F = np.zeros(n_students, dtype=np.float64)

    def _alpha0(self) -> float:
        return self.mu0 * self.kappa

    def _beta0(self) -> float:
        return (1.0 - self.mu0) * self.kappa

    def fit(self, binary: np.ndarray) -> None:
        n_days = len(binary)
        rates  = binary.mean(axis=0)

        # Method of Moments: E[θ] = μ₀, Var[θ] = μ₀(1-μ₀)/(κ₀+1)
        self.mu0 = float(rates.mean())
        var = float(rates.var())
        if var > 1e-8:
            kappa_mom = self.mu0 * (1.0 - self.mu0) / var - 1.0
            self.kappa = float(np.clip(kappa_mom, 2.0, 500.0))

        # Warm-start posteriors with all training data
        self.S = binary.sum(axis=0).astype(np.float64)
        self.F = (n_days - binary.sum(axis=0)).astype(np.float64)

        print(f"    μ₀={self.mu0:.4f}  κ₀={self.kappa:.1f}  "
              f"α₀={self._alpha0():.2f}  β₀={self._beta0():.2f}")
        pm = self._posterior_mean()
        print(f"    Posterior mean range: [{pm.min():.4f}, {pm.max():.4f}]")

    def _posterior_mean(self) -> np.ndarray:
        a = self._alpha0() + self.S
        b = self._beta0()  + self.F
        return (a / (a + b)).astype(np.float32)

    def predict(self) -> list[list[int]]:
        return _groups_from_probs(self._posterior_mean())

    def update(self, obs: np.ndarray) -> None:
        self.S += obs.astype(np.float64)
        self.F += (1.0 - obs).astype(np.float64)


# ══════════════════════════════════════════════════════════════════════════════
# 2. Dirichlet Process Mixture
# ══════════════════════════════════════════════════════════════════════════════

class DirichletProcessMixture:
    """
    Truncated Dirichlet Process Mixture (K_max clusters, stick-breaking).

    Generative model:
        V_k     ~ Beta(1, α_DP)                ← stick lengths
        π_k      = V_k · Π_{j<k}(1−V_j)         ← cluster weights
        θ_k     ~ Beta(a₀, b₀)               ← cluster calling probability
        z_s     ~ Categorical(π)              ← student cluster assignment
        x_s     ~ Bernoulli(θ_{z_s})          ← observation

    Inference:
        Variational EM — E-step (soft assignments) + M-step (cluster params)
        run for n_iter iterations on training data, then online after each day.

    Key property:
        Captures "teacher groups" — if the teacher tends to call certain
        clusters of students together, DPM clusters them and predicts them
        jointly via soft assignments.
    """

    def __init__(self, n_students: int = 55, K_max: int = 8,
                 alpha_dp: float = 2.0):
        self.N        = n_students
        self.K        = K_max
        self.alpha_dp = alpha_dp
        base          = 6.0 / n_students

        # Cluster Beta parameters
        self.a = np.ones(K_max, dtype=np.float64) * base * 20.0
        self.b = np.ones(K_max, dtype=np.float64) * (1.0 - base) * 20.0

        # Soft assignments (N × K) and cluster weights
        self.r  = np.ones((n_students, K_max), dtype=np.float64) / K_max
        self.pi = np.ones(K_max, dtype=np.float64) / K_max

        # Cumulative stats for online updates
        self.S_total = np.zeros(n_students, dtype=np.float64)
        self.n_total = 0.0

    def fit(self, binary: np.ndarray, n_iter: int = 30) -> None:
        n_days         = len(binary)
        self.S_total   = binary.sum(axis=0).astype(np.float64)
        self.n_total   = float(n_days)
        rates          = self.S_total / n_days

        # Initialise cluster means at evenly-spaced quantiles of student rates
        quantiles = np.percentile(rates, np.linspace(5, 95, self.K))
        for k, mu_k in enumerate(quantiles):
            mu_k = float(np.clip(mu_k, 0.01, 0.99))
            self.a[k] = mu_k * 20.0
            self.b[k] = (1.0 - mu_k) * 20.0

        # Variational EM
        for _ in range(n_iter):
            theta_k = self.a / (self.a + self.b)                        # (K,)

            # E-step: soft assignments
            log_r = np.zeros((self.N, self.K))
            for k in range(self.K):
                log_r[:, k] = (
                    self.S_total * np.log(theta_k[k] + 1e-10) +
                    (n_days - self.S_total) * np.log(1.0 - theta_k[k] + 1e-10) +
                    np.log(self.pi[k] + 1e-10)
                )
            log_r -= log_r.max(axis=1, keepdims=True)
            r = np.exp(log_r)
            r /= r.sum(axis=1, keepdims=True)
            self.r = r

            # M-step: cluster parameters
            N_k = r.sum(axis=0)                                          # (K,)
            for k in range(self.K):
                ws = float((r[:, k] * self.S_total).sum())
                wf = float((r[:, k] * (n_days - self.S_total)).sum())
                self.a[k] = 1.0 + ws
                self.b[k] = 1.0 + wf

            # VB stick-breaking weight update
            suffix_N  = np.cumsum(N_k[::-1])[::-1]
            beta_vb   = self.alpha_dp + suffix_N - N_k
            V         = (1.0 + N_k) / (1.0 + N_k + beta_vb)
            remaining = np.cumprod(np.concatenate([[1.0], 1.0 - V[:-1]]))
            pi        = V * remaining
            self.pi   = pi / pi.sum()

        theta_k = self.a / (self.a + self.b)
        print(f"    DPM K={self.K}, α_DP={self.alpha_dp}")
        print(f"    Cluster θ: {theta_k.round(3)}")
        print(f"    Cluster π: {self.pi.round(3)}")

    def _predict_probs(self) -> np.ndarray:
        theta_k = self.a / (self.a + self.b)                             # (K,)
        return (self.r * theta_k[None, :]).sum(axis=1).astype(np.float32)

    def predict(self) -> list[list[int]]:
        return _groups_from_probs(self._predict_probs())

    def update(self, obs: np.ndarray) -> None:
        self.S_total += obs.astype(np.float64)
        self.n_total += 1.0

        # Quick E-step
        theta_k = self.a / (self.a + self.b)
        log_r   = np.zeros((self.N, self.K))
        for k in range(self.K):
            log_r[:, k] = (
                self.S_total * np.log(theta_k[k] + 1e-10) +
                (self.n_total - self.S_total) * np.log(1.0 - theta_k[k] + 1e-10) +
                np.log(self.pi[k] + 1e-10)
            )
        log_r -= log_r.max(axis=1, keepdims=True)
        r = np.exp(log_r)
        r /= r.sum(axis=1, keepdims=True)
        self.r = r

        # Quick M-step
        for k in range(self.K):
            ws = float((r[:, k] * self.S_total).sum())
            wf = float((r[:, k] * (self.n_total - self.S_total)).sum())
            self.a[k] = 1.0 + ws
            self.b[k] = 1.0 + wf


# ══════════════════════════════════════════════════════════════════════════════
# 3. Pure Thompson Sampling
# ══════════════════════════════════════════════════════════════════════════════

class PureThompsonSampling:
    """
    Beta-Binomial Thompson Sampling — no decay, no cooldown, no clustering.

    Difference from existing BB:
        - BB uses decay γ=0.97 (recent days weighted more)
        - BB applies cooldown δ after selection
        - BB periodically refreshes hyperpriors

    PTS has NONE of those — raw Beta posteriors updated uniformly.
    This tests whether the BB's extra complexity (decay+cooldown+EB) helps,
    or if simple conjugate TS suffices.

    Group generation:
        Repeat n_groups×4 times:
            θ_s ~ Beta(α_s, β_s) for all 55 students
            group = top-6(θ)
        Keeps up to n_groups unique groups.
    """

    def __init__(self, n_students: int = 55, prior_strength: float = 2.0):
        base         = 6.0 / n_students
        self.alpha   = np.full(n_students, base * prior_strength,
                               dtype=np.float64)
        self.beta_   = np.full(n_students, (1.0 - base) * prior_strength,
                               dtype=np.float64)
        self.rng     = np.random.default_rng(SEED)

    def fit(self, binary: np.ndarray) -> None:
        self.alpha  += binary.sum(axis=0).astype(np.float64)
        self.beta_  += (len(binary) - binary.sum(axis=0)).astype(np.float64)
        pm = self.alpha / (self.alpha + self.beta_)
        print(f"    PTS posterior mean: [{pm.min():.4f}, {pm.max():.4f}]")
        print(f"    PTS α range: [{self.alpha.min():.1f}, {self.alpha.max():.1f}]")

    def predict(self) -> list[list[int]]:
        groups: list[list[int]] = []
        ng = CFG['n_groups']
        for _ in range(ng * 4):
            theta = self.rng.beta(self.alpha, self.beta_)
            g     = sorted(np.argsort(theta)[-CFG['k']:].tolist())
            if g not in groups:
                groups.append(g)
            if len(groups) >= ng:
                break
        if not groups:
            pm = self.alpha / (self.alpha + self.beta_)
            groups.append(sorted(np.argsort(pm)[-CFG['k']:].tolist()))
        return groups[:ng]

    def update(self, obs: np.ndarray) -> None:
        self.alpha  += obs.astype(np.float64)
        self.beta_  += (1.0 - obs).astype(np.float64)


# ══════════════════════════════════════════════════════════════════════════════
# Simulation runner
# ══════════════════════════════════════════════════════════════════════════════

def simulate(model, binary: np.ndarray, split: int, label: str) -> np.ndarray:
    n_sim = min(CFG['n_sim_days'], len(binary) - split)
    accs  = []
    t0    = time.perf_counter()

    for i in range(n_sim):
        actual = set(np.where(binary[split + i] == 1)[0].tolist())
        groups = model.predict()
        acc    = _best_overlap(groups, actual)
        accs.append(acc)

        if (i + 1) in {1, 10, 25, 50, 75, 100}:
            print(f"    Day {i+1:3d}: {acc*100:.1f}%  actual={sorted(actual)}")

        model.update(binary[split + i])

    arr = np.array(accs) * 100.0
    print(f"\n  ── {label} ──")
    print(f"  Avg: {arr.mean():.2f}%  Best: {arr.max():.2f}%  "
          f"Worst: {arr.min():.2f}%  Std: {arr.std():.4f}")
    dist = {k: int((arr == k / 6 * 100).sum()) for k in range(7)}
    non_zero = {k: v for k, v in dist.items() if v > 0}
    print(f"  Dist: " + "  ".join(f"{k}/6={v}" for k, v in non_zero.items()))
    print(f"  Time: {time.perf_counter()-t0:.1f}s")
    return arr


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    print("=" * 70)
    print("   ADVANCED BAYESIAN COMPARISON")
    print("   Hierarchical Bayesian | Dirichlet Process | Thompson Sampling")
    print("=" * 70)

    binary = load_binary()
    split  = int(len(binary) * CFG['train_ratio'])
    train  = binary[:split]
    print(f"\n  Data: {len(binary)} days  |  "
          f"Train: {split}  |  Test: {len(binary)-split}\n")

    results: dict[str, np.ndarray] = {}

    # ── 1. Hierarchical Bayesian ──────────────────────────────────────────────
    print("─" * 70)
    print("  [1/3]  HIERARCHICAL BAYESIAN  (partial pooling via shared prior)")
    print("─" * 70)
    hb = HierarchicalBayesian()
    hb.fit(train)
    results['Hierarchical Bayesian'] = simulate(hb, binary, split,
                                                'Hierarchical Bayesian')

    # ── 2. Dirichlet Process Mixture ─────────────────────────────────────────
    print("\n" + "─" * 70)
    print("  [2/3]  DIRICHLET PROCESS MIXTURE  (non-parametric clustering)")
    print("─" * 70)
    dpm = DirichletProcessMixture(K_max=8, alpha_dp=2.0)
    dpm.fit(train)
    results['Dirichlet Process Mix.'] = simulate(dpm, binary, split,
                                                  'Dirichlet Process Mixture')

    # ── 3. Pure Thompson Sampling ─────────────────────────────────────────────
    print("\n" + "─" * 70)
    print("  [3/3]  PURE THOMPSON SAMPLING  (conjugate, no decay/cooldown)")
    print("─" * 70)
    pts = PureThompsonSampling(prior_strength=2.0)
    pts.fit(train)
    results['Pure Thompson Sampling'] = simulate(pts, binary, split,
                                                  'Pure Thompson Sampling')

    # ── Final leaderboard ─────────────────────────────────────────────────────
    print("\n" + "=" * 70)
    print("  FULL LEADERBOARD  (100 days, 5 groups, best-of-5 overlap)")
    print("=" * 70)
    print(f"\n  {'Model':<30} {'Avg':>7} {'Best':>7} {'Worst':>7} {'Std':>8}")
    print(f"  {'─'*58}")

    # Benchmarks
    for name, avg in BENCHMARKS.items():
        print(f"  {name:<30} {avg:>6.2f}%  {'—':>7}  {'—':>7}  {'—':>8}  [prev]")

    print(f"  {'─'*58}")

    # New results
    all_avgs = list(BENCHMARKS.values())
    for name, arr in results.items():
        marker = " ← NEW BEST" if arr.mean() > max(BENCHMARKS.values()) else ""
        print(f"  {name:<30} {arr.mean():>6.2f}%  "
              f"{arr.max():>6.2f}%  {arr.min():>6.2f}%  {arr.std():>7.4f}{marker}")
        all_avgs.append(arr.mean())

    best_new_name = max(results, key=lambda k: results[k].mean())
    best_new_avg  = results[best_new_name].mean()
    best_bench    = max(BENCHMARKS.values())

    print(f"\n  Best new method  : {best_new_name}  ({best_new_avg:.2f}%)")
    print(f"  Best benchmark   : Hybrid Orig ({best_bench:.2f}%)")

    if best_new_avg > best_bench:
        print(f"\n  ✓ NEW BEST — {best_new_name} beats all existing models!")
    elif best_new_avg >= best_bench - 1.0:
        print(f"\n  ~ COMPETITIVE — within 1% of the benchmark.")
    else:
        print(f"\n  ✗ None of the new methods beat the benchmark.")
        print(f"    Gap: {best_bench - best_new_avg:.2f}%")

    print("\n" + "=" * 70)
    print("   ADVANCED BAYESIAN COMPARISON COMPLETE")
    print("=" * 70)
